[package]
name = "day4rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs-err = "2.6.0"
csv = "1.1.6"
itertools = "0.10.5"
